name: Deploy to Clever Cloud
description: Deploy your application to Clever Cloud
author: François Best
branding:
  icon: upload-cloud
  color: red
inputs:
  orgaID:
    required: true
    description: |
      The ID of your organization (can be found in the Clever Cloud console).
  type:
    required: true
    description: |
      The type of the application to deploy,
      if you are using a .clever.json file.
  region:
    required: false
    default: 'par'
    description: |
      The region to deploy the application to.
  alias:
    required: false
    default: ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}
    description: |
      The alias of the application to deploy,
      if you are using a .clever.json file.
  name:
    required: false
    default: ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}
    description: |
      The name of the application to deploy,
      if you are using a .clever.json file.
  domain:
    required: false
    default: ${{ github.event.pull_request.base.repo.name }}-PR-${{ github.event.number }}.cleverapps.io
    description: |
      The domain of the application to deploy
  appID:
    required: false
    description: |
      The ID of your application (can be found in the Clever Cloud console).
      Takes precedence over `alias` if both are defined.
  force:
    required: false
    default: 'false'
    description: |
      Use true if you want to force deploy even if it's not fast-forwardable
  timeout:
    required: false
    description: |
      How long (in seconds) to wait at most before moving on.
      This can help saving build minutes with very long deployments,
      but you will lose any deployment failure information.
  setEnv:
    required: false
    description: |
      Extra environment variables to set on the application before deployment.
      Values are separated by a newline character (\n), use a YAML literal block
      scalar `|` to preserve newlines and separate multiple variables definitions.
      (see https://github.com/47ng/actions-clever-cloud#extra-environment-variables)
  logFile:
    required: false
    description: |
      Path to a file where to store the deployment logs.
  quiet:
    required: false
    default: 'false'
    description: |
      Don't print deployment output to the console. Use this in case your deployment
      may reveal secrets or PII.
runs:
  using: docker
  image: docker://ghcr.io/47ng/actions-clever-cloud:v2.0.0
